db:
  mysql:
    hosts:
      - "120.0.0.1"
    port: 4000
    dataBase: "hydra"
    username: "root"
    password: ""
    max-idle-conn: 10
    max-open-conn: 100
    config: "charset=utf8mb4&parseTime=True&loc=Local"
    log-mode: "error"
  clickhouse:
    hosts:
      - "120.0.0.1:9000"
    dataBase: "hydra"
    username: "root"
    password: ""
    max-idle-conn: 10
    max-open-conn: 100
    is_debug: false

system:
  log_level: "info"
  path: "static"
  location_file: "IP2LOCATION-LITE-DB11.BIN"
  protocol_file: "protocol.json"
  protocol_key_file: "protocol_key.json"
  portrait_map_file: "portrait.json"
  area_file: "area.json"

session:
  expired: 20
  pcap_path: "/pcap"
  root_path: "/root"
