// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.0
// source: meta/meta_data.proto

package push_model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtocolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *uint32                `protobuf:"varint,1,req,name=type" json:"type,omitempty"`                                    //类型值与协议元数据TLV类型保持一致,见《协议元数据字段提取规范-v1.0.6》中“协议编号”
	ProtocolMeta  *anypb.Any             `protobuf:"bytes,2,req,name=protocol_meta,json=protocolMeta" json:"protocol_meta,omitempty"` //存储具体协议元数据(协议元数据pb参见protocol文件夹)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolInfo) Reset() {
	*x = ProtocolInfo{}
	mi := &file_meta_meta_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolInfo) ProtoMessage() {}

func (x *ProtocolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_meta_meta_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolInfo.ProtoReflect.Descriptor instead.
func (*ProtocolInfo) Descriptor() ([]byte, []int) {
	return file_meta_meta_data_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolInfo) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *ProtocolInfo) GetProtocolMeta() *anypb.Any {
	if x != nil {
		return x.ProtocolMeta
	}
	return nil
}

type MetaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolInfo  []*ProtocolInfo        `protobuf:"bytes,1,rep,name=protocol_info,json=protocolInfo" json:"protocol_info,omitempty"` //协议信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaInfo) Reset() {
	*x = MetaInfo{}
	mi := &file_meta_meta_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaInfo) ProtoMessage() {}

func (x *MetaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_meta_meta_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaInfo.ProtoReflect.Descriptor instead.
func (*MetaInfo) Descriptor() ([]byte, []int) {
	return file_meta_meta_data_proto_rawDescGZIP(), []int{1}
}

func (x *MetaInfo) GetProtocolInfo() []*ProtocolInfo {
	if x != nil {
		return x.ProtocolInfo
	}
	return nil
}

var File_meta_meta_data_proto protoreflect.FileDescriptor

var file_meta_meta_data_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x1a, 0x19, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x0d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x43, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x37, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x2f, 0x5a, 0x2d, 0x64,
	0x69, 0x73, 0x73, 0x65, 0x63, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x70,
	0x62, 0x3b, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
}

var (
	file_meta_meta_data_proto_rawDescOnce sync.Once
	file_meta_meta_data_proto_rawDescData = file_meta_meta_data_proto_rawDesc
)

func file_meta_meta_data_proto_rawDescGZIP() []byte {
	file_meta_meta_data_proto_rawDescOnce.Do(func() {
		file_meta_meta_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_meta_data_proto_rawDescData)
	})
	return file_meta_meta_data_proto_rawDescData
}

var file_meta_meta_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meta_meta_data_proto_goTypes = []any{
	(*ProtocolInfo)(nil), // 0: meta.ProtocolInfo
	(*MetaInfo)(nil),     // 1: meta.MetaInfo
	(*anypb.Any)(nil),    // 2: google.protobuf.Any
}
var file_meta_meta_data_proto_depIdxs = []int32{
	2, // 0: meta.ProtocolInfo.protocol_meta:type_name -> google.protobuf.Any
	0, // 1: meta.MetaInfo.protocol_info:type_name -> meta.ProtocolInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_meta_meta_data_proto_init() }
func file_meta_meta_data_proto_init() {
	if File_meta_meta_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_meta_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_meta_data_proto_goTypes,
		DependencyIndexes: file_meta_meta_data_proto_depIdxs,
		MessageInfos:      file_meta_meta_data_proto_msgTypes,
	}.Build()
	File_meta_meta_data_proto = out.File
	file_meta_meta_data_proto_rawDesc = nil
	file_meta_meta_data_proto_goTypes = nil
	file_meta_meta_data_proto_depIdxs = nil
}
