package asset

var (
	VendorMap = map[string]string{
		"Siemens":            "西门子",
		"Schneider":          "施耐德",
		"OMRON":              "欧姆龙",
		"Yaskawa":            "安川",
		"Kawasaki":           "川崎",
		"Beckhoff":           "德国倍福",
		"Fanuc":              "发那科",
		"Phoenix":            "菲尼克斯电气",
		"Yokogawa":           "横河电机",
		"RedLion":            "红狮",
		"Honeywell":          "霍尼韦尔",
		"Comau":              "柯马",
		"KUKA":               "库卡",
		"Rockwell":           "罗克韦尔",
		"Moxa":               "摩莎",
		"Nachi":              "那智不二越",
		"Mitsubishi":         "三菱",
		"Delta":              "台达",
		"GE":                 "通用",
		"Wago":               "万可",
		"YAMAHA":             "雅马哈",
		"Advantech":          "研华科技",
		"EdmWebVideo":        "EdmWebVideo",
		"NEAT":               "尼特",
		"TCL":                "TCL王牌",
		"TPLINK":             "TPLINK",
		"Axis":               "安讯士",
		"Bosch":              "博世",
		"SKYWORTH":           "创维",
		"Dahua":              "大华",
		"HIKVISION":          "海康威视",
		"Hanwha":             "韩华",
		"HANBANGGAOKE":       "汉邦高科",
		"Macro-Video":        "宏视电子",
		"JIALAJIAHE":         "佳联佳合",
		"JUANCLOUD":          "九安",
		"KEDACOM":            "科达股份",
		"Lanpeng":            "蓝鹏",
		"LUOWICE":            "镭威视",
		"iSmartVision":       "迈特威视",
		"JOOAN":              "乔安",
		"Samsung":            "三星",
		"Panasonic":          "松下",
		"Sony":               "索尼",
		"Tiandy":             "天地伟业",
		"TVT":                "同为",
		"SEEYOO":             "信颐",
		"XM":                 "雄迈",
		"YINSHA":             "银鲨",
		"lnfinova":           "英飞拓",
		"EMA":                "英码",
		"uniview":            "宇视",
		"ZKTeco":             "中控智慧",
		"ZTE":                "中兴通讯",
		"ECHELON":            "埃施朗",
		"Epson":              "爱普生",
		"Aizhi":              "爱智",
		"Lantronix":          "创力",
		"FANUC":              "发那科",
		"PhoenixContact":     "菲尼克斯电气",
		"GSK":                "广数",
		"Hikvision":          "海康",
		"HollySys":           "和利时",
		"Hongdian":           "宏电",
		"Inovance":           "汇川",
		"IESLob":             "积成电子",
		"Geek+":              "极智嘉",
		"FameView":           "杰控科技",
		"JD":                 "京东",
		"Quicktron":          "快仓",
		"kunlunjichuang":     "昆仑通态",
		"Quantum":            "昆腾",
		"Kingview":           "力控",
		"RockwellAutomation": "罗克韦尔",
		"Omron":              "欧姆龙",
		"MitsubishiElectric": "三菱电机",
		"Schneider Electric": "施耐德",
		"staubli":            "史陶比尔",
		"SAP":                "思爱普",
		"General Electric":   "通用电气",
		"WAGO":               "万可",
		"Siasun":             "新松",
		"WellinTech":         "亚控科技",
		"EVOC":               "研祥",
		"SUPCON":             "浙大中控",
		"ICSAS":              "中科院软件所",
		"realinfo":           "紫金桥",
		"iotrouter":          "纵横智控",
		"ForceControl":       "力控",
		"OSIsoft":            "OSIsoft",
		"Tridium":            "Tridium",
		"OTC":                "OTC",
		"ABB":                "ABB",
		"UR":                 "UR",
		"Yaskawa Electric America formerly Magnetek Drives": "安川",
		"Kawasaki Robotics (USA), Inc.":                     "川崎",
		"Kawasaki Robotics":                                 "川崎",
		"Beckhoff Automation GmbH":                          "德国倍福",
		"Fanuc Robotics America":                            "发那科",
		"Phoenix Contact":                                   "菲尼克斯电气",
		"Yokogawa Electric Corporation":                     "横河电机",
		"Red Lion Controls":                                 "红狮",
		"Honeywell Inc.":                                    "霍尼韦尔",
		"Comau S.p.A. Robotics & Final Assembly Division":   "柯马",
		"KUKA Roboter GmbH":                                 "库卡",
		"Rockwell Automation/Allen-Bradley":                 "罗克韦尔",
		"Moxa Networking Co., Ltd.":                         "摩莎",
		"Nachi Fujikoshi Corporation":                       "那智不二越",
		"Omron Corporation":                                 "欧姆龙",
		"Mitsubishi Heavy Industries Ltd":                   "三菱",
		"Mitsubishi Electric Engineering Co., Ltd.":         "三菱电机",
		"Delta Electronic Inc.":                             "台达",
		"GE Industrial Systems":                             "通用电气",
		"Wago Corporation":                                  "万可",
		"YAMAHA Motor Co. Ltd.":                             "雅马哈",
		"Advantech Co. Ltd.":                                "研华科技",
		"ABB Robotics Products AB":                          "ABB",
		"1000":                                              "创维SKYWORTH",
		"1001":                                              "大华",
		"1002":                                              "同为",
		"1003":                                              "天地伟业",
		"1004":                                              "乔安JOOAN",
		"1005":                                              "佳联佳合JIALAJIAHE",
		"1006":                                              "英码",
		"1007":                                              "NEAT尼特",
		"1008":                                              "Advantech",
		"1009":                                              "雄迈",
		"1010":                                              "迈特威视",
		"1011":                                              "韩华",
		"1012":                                              "宏视电子",
		"1013":                                              "汉邦高科",
		"1014":                                              "博世",
		"1015":                                              "IoT",
		"1016":                                              "霍尼韦尔",
		"1017":                                              "科达股份",
		"1018":                                              "三星",
		"1019":                                              "海康威视",
		"1020":                                              "EdmWebVideo",
		"1021":                                              "宇视",
		"1022":                                              "信颐SII",
		"1023":                                              "松下",
		"1024":                                              "安讯士",
		"1025":                                              "九安",
		"1026":                                              "TPLINK",
		"1027":                                              "索尼",
		"1028":                                              "中控智慧",
		"1029":                                              "英飞拓",
		"1030":                                              "中兴通讯ZTE",
		"1031":                                              "镭威视LUOWICE",
		"1032":                                              "银鲨YINSHA",
		"1033":                                              "TCL王牌",
		"1034":                                              "蓝鹏",
		"1035":                                              "MQTT",
		"2000":                                              "广数",
		"2001":                                              "和利时",
		"2002":                                              "浙大中控",
		"2003":                                              "DICOM",
		"2004":                                              "爱智",
		"2005":                                              "Wonderware",
		"2006":                                              "京东",
		"2007":                                              "霍尼韦尔",
		"2008":                                              "通用电气",
		"2009":                                              "雅马哈",
		"2010":                                              "力控",
		"2011":                                              "宏电",
		"2012":                                              "西门子",
		"2013":                                              "Kepware",
		"2014":                                              "研华科技",
		"2015":                                              "汇川",
		"2016":                                              "UR",
		"2017":                                              "Opto22",
		"2018":                                              "台达",
		"2019":                                              "杰控科技",
		"2020":                                              "三菱电机",
		"2021":                                              "罗克韦尔",
		"2022":                                              "海康",
		"2023":                                              "思爱普",
		"2024":                                              "创力",
		"2025":                                              "昆腾",
		"2026":                                              "eDNA",
		"2027":                                              "Tridium",
		"2028":                                              "安川",
		"2029":                                              "发那科",
		"2030":                                              "DigitalElectronics",
		"2031":                                              "BeckhoffAutomation",
		"2032":                                              "三菱",
		"2033":                                              "库卡",
		"2034":                                              "OTC",
		"2035":                                              "HJ212",
		"2036":                                              "中科院软件所",
		"2037":                                              "爱普生",
		"2038":                                              "红狮",
		"2039":                                              "施耐德",
		"2040":                                              "史陶比尔",
		"2041":                                              "摩莎",
		"2042":                                              "3S-SmartSoftware",
		"2043":                                              "德国倍福",
		"2044":                                              "川崎",
		"2045":                                              "OSIsoft",
		"2046":                                              "快仓",
		"2047":                                              "纵横智控",
		"2048":                                              "ABB",
		"2049":                                              "亚控科技",
		"2050":                                              "研祥",
		"2051":                                              "那智不二越",
		"2052":                                              "埃施朗",
		"2053":                                              "极智嘉",
		"2054":                                              "Digi",
		"2055":                                              "紫金桥",
		"2056":                                              "积成电子",
		"2057":                                              "BACnet",
		"2058":                                              "ICS",
		"2059":                                              "欧姆龙",
		"2060":                                              "柯马",
		"2061":                                              "WAGO",
		"2062":                                              "新松",
		"2063":                                              "万可",
		"2064":                                              "昆仑通态",
		"2065":                                              "菲尼克斯电气",
		"2066":                                              "横河电机",
	}

	typeMap = map[string]string{
		"10": "指纹门禁设备",
		"11": "视频监控设备",
		"12": "IOT",
		"13": "Mobile",
		"14": "Device",
		"15": "IOT",
		"16": "RTDB",
		"17": "HMI",
		"18": "医疗系统",
		"19": "加油站液位仪",
		"20": "DTU",
		"21": "环保监测系统",
		"22": "串口转换服务",
		"23": "EtherNetIP",
		"24": "串口服务器",
		"25": "水利系统",
		"26": "ICS",
		"27": "WinCE",
		"28": "Software",
		"29": "电力系统",
		"30": "AGV",
		"31": "机器人",
		"32": "SCADA",
		"33": "OPCUA",
		"34": "Modbus",
		"35": "PLC",
	}

	DeviceModelMap = map[string]string{
		"5514": "EKI-5525S-SC",
		"5515": "EKI-5525S",
		"b571": "ADAM-4571L",
		"4572": "ADAM-4572",
		"5511": "EKI-5525M-ST",
		"5512": "EKI-5525M-SC",
		"5505": "EKI-5525M",
		"5525": "EKI-5525",
		"5523": "EKI-5524SS-ST",
		"5524": "EKI-5524SS-SC",
		"552f": "EKI-5524SS",
		"5521": "EKI-5524MM-ST",
		"5522": "EKI-5524MM-SC",
		"551f": "EKI-5524MM",
		"b528": "EKI-1528-BE",
		"1528": "EKI-1528",
		"b526": "EKI-1526-BE",
		"1526": "EKI-1526",
		"b524": "EKI-1524-BE",
		"1524": "EKI-1524",
		"d522": "EKI-1522D",
		"b522": "EKI-1522-BE",
		"1522": "EKI-1522",
		"d521": "EKI-1521D",
		"b521": "EKI-1521-BE",
		"1521": "EKI-1521",
		"1512": "EKI-1512X-AE",
		"1511": "EKI-1511X-AE",
		"1362": "EKI-1362",
		"1361": "EKI-1361",
		"1352": "EKI-1352",
		"1351": "EKI-1351",
		"1322": "EKI-1322",
		"1321": "EKI-1321",
		"b224": "EKI-1224-BE",
		"1224": "EKI-1224",
		"d222": "EKI-1222D",
		"b222": "EKI-1222-BE",
		"1222": "EKI-1222",
		"d221": "EKI-1221D",
		"b221": "EKI-1221-BE",
		"1221": "EKI-1221",
		"4516": "EDG-4516(R)+",
		"4508": "EDG-4508(R)+",
		"4504": "EDG-4504",
		"4579": "ADAM-4579",
		"4577": "ADAM-4577",
		"b572": "ADAM-4572-CE",
		"c571": "ADAM-4571W",
		"4571": "ADAM-4571",
		"e571": "ADAM-4571L-DE",
		"d571": "ADAM-4571-CE",
		"c570": "ADAM-4570W",
		"4570": "ADAM-4570",
		"b570": "ADAM-4570L",
		"e570": "ADAM-4570L-DE",
		"d570": "ADAM-4570-CE",
		"5719": "EKI-5729P",
		"5729": "EKI-5729F",
		"5718": "EKI-5728P",
		"5728": "EKI-5728",
		"5716": "EKI-5726F",
		"5726": "EKI-5726",
		"5705": "EKI-5725P",
		"5715": "EKI-5725FP",
		"5725": "EKI-5725",
		"5629": "EKI-5629C",
		"5626": "EKI-5626C",
		"5624": "EKI-5624P",
		"5528": "EKI-5528",
		"5526": "EKI-5526",
		"5513": "EKI-5525S-ST",
	}
)
