// generated by directives_generate.go; DO NOT EDIT

package module

import (
	// Include all plugins.

	_ "dissect/internal/plugin/asset"
	_ "dissect/internal/plugin/exception"
	_ "dissect/internal/plugin/portrait"
	_ "dissect/internal/plugin/protocol_explain"
	_ "dissect/internal/plugin/session"
	_ "dissect/internal/plugin/store"
	_ "dissect/internal/plugin/warn"
)
