// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.0
// source: meta/protocol/enip.proto

package push_model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnipInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Cmd             *uint32                `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	Length          *uint32                `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	Session         *uint32                `protobuf:"varint,3,opt,name=session" json:"session,omitempty"`
	Status          *uint32                `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`
	Context         *string                `protobuf:"bytes,5,opt,name=context" json:"context,omitempty"`
	SocketInnerIp   *string                `protobuf:"bytes,6,opt,name=socketInnerIp" json:"socketInnerIp,omitempty"`
	SocketInnerPort *uint32                `protobuf:"varint,7,opt,name=socketInnerPort" json:"socketInnerPort,omitempty"`
	Vendor          *uint32                `protobuf:"varint,8,opt,name=vendor" json:"vendor,omitempty"`
	Type            *uint32                `protobuf:"varint,9,opt,name=type" json:"type,omitempty"`
	Name            *string                `protobuf:"bytes,10,opt,name=name" json:"name,omitempty"`
	Sn              *uint32                `protobuf:"varint,11,opt,name=sn" json:"sn,omitempty"`
	FirmwareVersion *string                `protobuf:"bytes,12,opt,name=firmwareVersion" json:"firmwareVersion,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnipInfo) Reset() {
	*x = EnipInfo{}
	mi := &file_meta_protocol_enip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnipInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnipInfo) ProtoMessage() {}

func (x *EnipInfo) ProtoReflect() protoreflect.Message {
	mi := &file_meta_protocol_enip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnipInfo.ProtoReflect.Descriptor instead.
func (*EnipInfo) Descriptor() ([]byte, []int) {
	return file_meta_protocol_enip_proto_rawDescGZIP(), []int{0}
}

func (x *EnipInfo) GetCmd() uint32 {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return 0
}

func (x *EnipInfo) GetLength() uint32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *EnipInfo) GetSession() uint32 {
	if x != nil && x.Session != nil {
		return *x.Session
	}
	return 0
}

func (x *EnipInfo) GetStatus() uint32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *EnipInfo) GetContext() string {
	if x != nil && x.Context != nil {
		return *x.Context
	}
	return ""
}

func (x *EnipInfo) GetSocketInnerIp() string {
	if x != nil && x.SocketInnerIp != nil {
		return *x.SocketInnerIp
	}
	return ""
}

func (x *EnipInfo) GetSocketInnerPort() uint32 {
	if x != nil && x.SocketInnerPort != nil {
		return *x.SocketInnerPort
	}
	return 0
}

func (x *EnipInfo) GetVendor() uint32 {
	if x != nil && x.Vendor != nil {
		return *x.Vendor
	}
	return 0
}

func (x *EnipInfo) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *EnipInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EnipInfo) GetSn() uint32 {
	if x != nil && x.Sn != nil {
		return *x.Sn
	}
	return 0
}

func (x *EnipInfo) GetFirmwareVersion() string {
	if x != nil && x.FirmwareVersion != nil {
		return *x.FirmwareVersion
	}
	return ""
}

var File_meta_protocol_enip_proto protoreflect.FileDescriptor

var file_meta_protocol_enip_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x65, 0x6e, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x22, 0xca, 0x02, 0x0a, 0x08, 0x45, 0x6e, 0x69, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x6e, 0x6e,
	0x65, 0x72, 0x49, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x70, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0f, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x73, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x66, 0x69, 0x72, 0x6d, 0x77, 0x61, 0x72, 0x65, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x66, 0x69,
	0x72, 0x6d, 0x77, 0x61, 0x72, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x2f, 0x5a,
	0x2d, 0x64, 0x69, 0x73, 0x73, 0x65, 0x63, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x2f, 0x70, 0x62, 0x3b, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
}

var (
	file_meta_protocol_enip_proto_rawDescOnce sync.Once
	file_meta_protocol_enip_proto_rawDescData = file_meta_protocol_enip_proto_rawDesc
)

func file_meta_protocol_enip_proto_rawDescGZIP() []byte {
	file_meta_protocol_enip_proto_rawDescOnce.Do(func() {
		file_meta_protocol_enip_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_protocol_enip_proto_rawDescData)
	})
	return file_meta_protocol_enip_proto_rawDescData
}

var file_meta_protocol_enip_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meta_protocol_enip_proto_goTypes = []any{
	(*EnipInfo)(nil), // 0: meta.EnipInfo
}
var file_meta_protocol_enip_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_protocol_enip_proto_init() }
func file_meta_protocol_enip_proto_init() {
	if File_meta_protocol_enip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_protocol_enip_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_protocol_enip_proto_goTypes,
		DependencyIndexes: file_meta_protocol_enip_proto_depIdxs,
		MessageInfos:      file_meta_protocol_enip_proto_msgTypes,
	}.Build()
	File_meta_protocol_enip_proto = out.File
	file_meta_protocol_enip_proto_rawDesc = nil
	file_meta_protocol_enip_proto_goTypes = nil
	file_meta_protocol_enip_proto_depIdxs = nil
}
