// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.0
// source: meta/protocol/ics.proto

package push_model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ICSInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SysVer        *string                `protobuf:"bytes,1,opt,name=sysVer" json:"sysVer,omitempty"`
	PortID        *string                `protobuf:"bytes,2,opt,name=portID" json:"portID,omitempty"`
	ResOfPort     *string                `protobuf:"bytes,3,opt,name=resOfPort" json:"resOfPort,omitempty"`
	UsrName       *string                `protobuf:"bytes,4,opt,name=usrName" json:"usrName,omitempty"`
	Pwd           *string                `protobuf:"bytes,5,opt,name=pwd" json:"pwd,omitempty"`
	InfoOfSoft    *string                `protobuf:"bytes,6,opt,name=infoOfSoft" json:"infoOfSoft,omitempty"`
	RunRec        *string                `protobuf:"bytes,7,opt,name=runRec" json:"runRec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICSInfo) Reset() {
	*x = ICSInfo{}
	mi := &file_meta_protocol_ics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICSInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICSInfo) ProtoMessage() {}

func (x *ICSInfo) ProtoReflect() protoreflect.Message {
	mi := &file_meta_protocol_ics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICSInfo.ProtoReflect.Descriptor instead.
func (*ICSInfo) Descriptor() ([]byte, []int) {
	return file_meta_protocol_ics_proto_rawDescGZIP(), []int{0}
}

func (x *ICSInfo) GetSysVer() string {
	if x != nil && x.SysVer != nil {
		return *x.SysVer
	}
	return ""
}

func (x *ICSInfo) GetPortID() string {
	if x != nil && x.PortID != nil {
		return *x.PortID
	}
	return ""
}

func (x *ICSInfo) GetResOfPort() string {
	if x != nil && x.ResOfPort != nil {
		return *x.ResOfPort
	}
	return ""
}

func (x *ICSInfo) GetUsrName() string {
	if x != nil && x.UsrName != nil {
		return *x.UsrName
	}
	return ""
}

func (x *ICSInfo) GetPwd() string {
	if x != nil && x.Pwd != nil {
		return *x.Pwd
	}
	return ""
}

func (x *ICSInfo) GetInfoOfSoft() string {
	if x != nil && x.InfoOfSoft != nil {
		return *x.InfoOfSoft
	}
	return ""
}

func (x *ICSInfo) GetRunRec() string {
	if x != nil && x.RunRec != nil {
		return *x.RunRec
	}
	return ""
}

var File_meta_protocol_ics_proto protoreflect.FileDescriptor

var file_meta_protocol_ics_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22,
	0xbb, 0x01, 0x0a, 0x07, 0x49, 0x43, 0x53, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x79, 0x73, 0x56, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x73,
	0x56, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x72,
	0x65, 0x73, 0x4f, 0x66, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x65, 0x73, 0x4f, 0x66, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x70, 0x77, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x66, 0x6f, 0x4f, 0x66, 0x53,
	0x6f, 0x66, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x66, 0x6f, 0x4f,
	0x66, 0x53, 0x6f, 0x66, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x75, 0x6e, 0x52, 0x65, 0x63, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x75, 0x6e, 0x52, 0x65, 0x63, 0x42, 0x2f, 0x5a,
	0x2d, 0x64, 0x69, 0x73, 0x73, 0x65, 0x63, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x2f, 0x70, 0x62, 0x3b, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
}

var (
	file_meta_protocol_ics_proto_rawDescOnce sync.Once
	file_meta_protocol_ics_proto_rawDescData = file_meta_protocol_ics_proto_rawDesc
)

func file_meta_protocol_ics_proto_rawDescGZIP() []byte {
	file_meta_protocol_ics_proto_rawDescOnce.Do(func() {
		file_meta_protocol_ics_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_protocol_ics_proto_rawDescData)
	})
	return file_meta_protocol_ics_proto_rawDescData
}

var file_meta_protocol_ics_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meta_protocol_ics_proto_goTypes = []any{
	(*ICSInfo)(nil), // 0: meta.ICSInfo
}
var file_meta_protocol_ics_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_protocol_ics_proto_init() }
func file_meta_protocol_ics_proto_init() {
	if File_meta_protocol_ics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_protocol_ics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_protocol_ics_proto_goTypes,
		DependencyIndexes: file_meta_protocol_ics_proto_depIdxs,
		MessageInfos:      file_meta_protocol_ics_proto_msgTypes,
	}.Build()
	File_meta_protocol_ics_proto = out.File
	file_meta_protocol_ics_proto_rawDesc = nil
	file_meta_protocol_ics_proto_goTypes = nil
	file_meta_protocol_ics_proto_depIdxs = nil
}
