// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.0
// source: meta/protocol/iec104.proto

package push_model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Iec104Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cptimemin     *int64                 `protobuf:"varint,1,opt,name=cptimemin" json:"cptimemin,omitempty"`  //20	分钟
	Numix         *uint32                `protobuf:"varint,2,opt,name=numix" json:"numix,omitempty"`          //	信息体地址的序号
	Ioa           *uint32                `protobuf:"varint,3,opt,name=ioa" json:"ioa,omitempty"`              //	信息对象地址
	Cptimems      *int64                 `protobuf:"varint,4,opt,name=cptimems" json:"cptimems,omitempty"`    //毫秒部分时间
	Cptimesu      *bool                  `protobuf:"varint,5,opt,name=cptimesu" json:"cptimesu,omitempty"`    //	状态更新标志位
	Cptimeday     *int64                 `protobuf:"varint,6,opt,name=cptimeday" json:"cptimeday,omitempty"`  //日（日期中的日）
	Typeid        *uint32                `protobuf:"varint,7,opt,name=typeid" json:"typeid,omitempty"`        //IEC60870 数据单元类型标识
	Coi           *uint32                `protobuf:"varint,8,opt,name=coi" json:"coi,omitempty"`              //信息对象标识符的类别
	Sq            *bool                  `protobuf:"varint,9,opt,name=sq" json:"sq,omitempty"`                //单点遥信状态或序列信息
	Addr          *uint32                `protobuf:"varint,10,opt,name=addr" json:"addr,omitempty"`           //IEC60870 数据单元地址
	Cptimedow     *uint32                `protobuf:"varint,11,opt,name=cptimedow" json:"cptimedow,omitempty"` //星期几（Day Of Week）
	Utype         *uint32                `protobuf:"varint,12,opt,name=utype" json:"utype,omitempty"`         //IEC60870-104 消息类型
	Type          *uint32                `protobuf:"varint,13,opt,name=type" json:"type,omitempty"`           //	IEC60870-104 消息类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Iec104Info) Reset() {
	*x = Iec104Info{}
	mi := &file_meta_protocol_iec104_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Iec104Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Iec104Info) ProtoMessage() {}

func (x *Iec104Info) ProtoReflect() protoreflect.Message {
	mi := &file_meta_protocol_iec104_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Iec104Info.ProtoReflect.Descriptor instead.
func (*Iec104Info) Descriptor() ([]byte, []int) {
	return file_meta_protocol_iec104_proto_rawDescGZIP(), []int{0}
}

func (x *Iec104Info) GetCptimemin() int64 {
	if x != nil && x.Cptimemin != nil {
		return *x.Cptimemin
	}
	return 0
}

func (x *Iec104Info) GetNumix() uint32 {
	if x != nil && x.Numix != nil {
		return *x.Numix
	}
	return 0
}

func (x *Iec104Info) GetIoa() uint32 {
	if x != nil && x.Ioa != nil {
		return *x.Ioa
	}
	return 0
}

func (x *Iec104Info) GetCptimems() int64 {
	if x != nil && x.Cptimems != nil {
		return *x.Cptimems
	}
	return 0
}

func (x *Iec104Info) GetCptimesu() bool {
	if x != nil && x.Cptimesu != nil {
		return *x.Cptimesu
	}
	return false
}

func (x *Iec104Info) GetCptimeday() int64 {
	if x != nil && x.Cptimeday != nil {
		return *x.Cptimeday
	}
	return 0
}

func (x *Iec104Info) GetTypeid() uint32 {
	if x != nil && x.Typeid != nil {
		return *x.Typeid
	}
	return 0
}

func (x *Iec104Info) GetCoi() uint32 {
	if x != nil && x.Coi != nil {
		return *x.Coi
	}
	return 0
}

func (x *Iec104Info) GetSq() bool {
	if x != nil && x.Sq != nil {
		return *x.Sq
	}
	return false
}

func (x *Iec104Info) GetAddr() uint32 {
	if x != nil && x.Addr != nil {
		return *x.Addr
	}
	return 0
}

func (x *Iec104Info) GetCptimedow() uint32 {
	if x != nil && x.Cptimedow != nil {
		return *x.Cptimedow
	}
	return 0
}

func (x *Iec104Info) GetUtype() uint32 {
	if x != nil && x.Utype != nil {
		return *x.Utype
	}
	return 0
}

func (x *Iec104Info) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

var File_meta_protocol_iec104_proto protoreflect.FileDescriptor

var file_meta_protocol_iec104_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x69, 0x65, 0x63, 0x31, 0x30, 0x34, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x65,
	0x74, 0x61, 0x22, 0xbe, 0x02, 0x0a, 0x0a, 0x49, 0x65, 0x63, 0x31, 0x30, 0x34, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x6d, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x6d, 0x69, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x75, 0x6d, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6e, 0x75, 0x6d, 0x69, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6f, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x69, 0x6f, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x70, 0x74, 0x69, 0x6d,
	0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x70, 0x74, 0x69, 0x6d,
	0x65, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x75, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x75, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x64, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x63, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x64, 0x61, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x79, 0x70, 0x65, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74,
	0x79, 0x70, 0x65, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6f, 0x69, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x63, 0x6f, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x71, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x73, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x70, 0x74, 0x69, 0x6d, 0x65, 0x64, 0x6f, 0x77, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x63, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x64, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x75, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x64, 0x69, 0x73, 0x73, 0x65, 0x63, 0x74, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c,
}

var (
	file_meta_protocol_iec104_proto_rawDescOnce sync.Once
	file_meta_protocol_iec104_proto_rawDescData = file_meta_protocol_iec104_proto_rawDesc
)

func file_meta_protocol_iec104_proto_rawDescGZIP() []byte {
	file_meta_protocol_iec104_proto_rawDescOnce.Do(func() {
		file_meta_protocol_iec104_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_protocol_iec104_proto_rawDescData)
	})
	return file_meta_protocol_iec104_proto_rawDescData
}

var file_meta_protocol_iec104_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meta_protocol_iec104_proto_goTypes = []any{
	(*Iec104Info)(nil), // 0: meta.Iec104Info
}
var file_meta_protocol_iec104_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_protocol_iec104_proto_init() }
func file_meta_protocol_iec104_proto_init() {
	if File_meta_protocol_iec104_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_protocol_iec104_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_protocol_iec104_proto_goTypes,
		DependencyIndexes: file_meta_protocol_iec104_proto_depIdxs,
		MessageInfos:      file_meta_protocol_iec104_proto_msgTypes,
	}.Build()
	File_meta_protocol_iec104_proto = out.File
	file_meta_protocol_iec104_proto_rawDesc = nil
	file_meta_protocol_iec104_proto_goTypes = nil
	file_meta_protocol_iec104_proto_depIdxs = nil
}
