// generated by directives_generate.go; DO NOT EDIT

package core

// Directives are registered in the order they should be
// executed.
//
// Ordering is VERY important. Every plugin will
// feel the effects of all other plugin below
// (after) them during a request, but they must not
// care what plugin above them are doing.
var Directives = []string{
	"exception",
	"explain",
	"asset",
	"portrait",
	"warn",
	"session",
	"store",
}
