// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.0
// source: base/ip_info.proto

package push_model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IP_INFO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            *string                `protobuf:"bytes,1,req,name=ip" json:"ip,omitempty"`                                        // IP地址
	Port          *uint32                `protobuf:"varint,2,req,name=port" json:"port,omitempty"`                                   // 端口
	IpCountry     *string                `protobuf:"bytes,3,req,name=ip_country,json=ipCountry" json:"ip_country,omitempty"`         // 国家名
	IpStat        *string                `protobuf:"bytes,4,req,name=ip_stat,json=ipStat" json:"ip_stat,omitempty"`                  // 省份/洲名
	IpCity        *string                `protobuf:"bytes,5,req,name=ip_city,json=ipCity" json:"ip_city,omitempty"`                  // 城市名
	IpOrg         *string                `protobuf:"bytes,6,req,name=ip_org,json=ipOrg" json:"ip_org,omitempty"`                     // 机构名
	IpLongitude   *float64               `protobuf:"fixed64,7,req,name=ip_longitude,json=ipLongitude" json:"ip_longitude,omitempty"` // 纬度
	IpLatitude    *float64               `protobuf:"fixed64,8,req,name=ip_latitude,json=ipLatitude" json:"ip_latitude,omitempty"`    // 经度
	IpIsp         *string                `protobuf:"bytes,9,req,name=ip_isp,json=ipIsp" json:"ip_isp,omitempty"`                     // 运营商
	IpAsn         *string                `protobuf:"bytes,10,req,name=ip_asn,json=ipAsn" json:"ip_asn,omitempty"`                    // AS信息
	IpTag         *string                `protobuf:"bytes,11,opt,name=ip_tag,json=ipTag" json:"ip_tag,omitempty"`                    // 标签
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IP_INFO) Reset() {
	*x = IP_INFO{}
	mi := &file_base_ip_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IP_INFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IP_INFO) ProtoMessage() {}

func (x *IP_INFO) ProtoReflect() protoreflect.Message {
	mi := &file_base_ip_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IP_INFO.ProtoReflect.Descriptor instead.
func (*IP_INFO) Descriptor() ([]byte, []int) {
	return file_base_ip_info_proto_rawDescGZIP(), []int{0}
}

func (x *IP_INFO) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *IP_INFO) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *IP_INFO) GetIpCountry() string {
	if x != nil && x.IpCountry != nil {
		return *x.IpCountry
	}
	return ""
}

func (x *IP_INFO) GetIpStat() string {
	if x != nil && x.IpStat != nil {
		return *x.IpStat
	}
	return ""
}

func (x *IP_INFO) GetIpCity() string {
	if x != nil && x.IpCity != nil {
		return *x.IpCity
	}
	return ""
}

func (x *IP_INFO) GetIpOrg() string {
	if x != nil && x.IpOrg != nil {
		return *x.IpOrg
	}
	return ""
}

func (x *IP_INFO) GetIpLongitude() float64 {
	if x != nil && x.IpLongitude != nil {
		return *x.IpLongitude
	}
	return 0
}

func (x *IP_INFO) GetIpLatitude() float64 {
	if x != nil && x.IpLatitude != nil {
		return *x.IpLatitude
	}
	return 0
}

func (x *IP_INFO) GetIpIsp() string {
	if x != nil && x.IpIsp != nil {
		return *x.IpIsp
	}
	return ""
}

func (x *IP_INFO) GetIpAsn() string {
	if x != nil && x.IpAsn != nil {
		return *x.IpAsn
	}
	return ""
}

func (x *IP_INFO) GetIpTag() string {
	if x != nil && x.IpTag != nil {
		return *x.IpTag
	}
	return ""
}

var File_base_ip_info_proto protoreflect.FileDescriptor

var file_base_ip_info_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x69, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x9e, 0x02,
	0x0a, 0x07, 0x49, 0x50, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x09, 0x69, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x70, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x18, 0x04, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x69,
	0x70, 0x53, 0x74, 0x61, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x70, 0x5f, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x05, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x69, 0x70, 0x43, 0x69, 0x74, 0x79, 0x12, 0x15,
	0x0a, 0x06, 0x69, 0x70, 0x5f, 0x6f, 0x72, 0x67, 0x18, 0x06, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x70, 0x4f, 0x72, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x70, 0x5f, 0x6c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x07, 0x20, 0x02, 0x28, 0x01, 0x52, 0x0b, 0x69, 0x70, 0x4c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x70, 0x5f, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x08, 0x20, 0x02, 0x28, 0x01, 0x52, 0x0a, 0x69,
	0x70, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x70, 0x5f,
	0x69, 0x73, 0x70, 0x18, 0x09, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x69, 0x70, 0x49, 0x73, 0x70,
	0x12, 0x15, 0x0a, 0x06, 0x69, 0x70, 0x5f, 0x61, 0x73, 0x6e, 0x18, 0x0a, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x05, 0x69, 0x70, 0x41, 0x73, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x70, 0x5f, 0x74, 0x61,
	0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x70, 0x54, 0x61, 0x67, 0x42, 0x5c,
	0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x62, 0x61, 0x73, 0x65,
	0x42, 0x06, 0x49, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x5a, 0x32, 0x64, 0x69, 0x73, 0x73, 0x65, 0x63,
	0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x61, 0x73,
	0x65, 0x3b, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
}

var (
	file_base_ip_info_proto_rawDescOnce sync.Once
	file_base_ip_info_proto_rawDescData = file_base_ip_info_proto_rawDesc
)

func file_base_ip_info_proto_rawDescGZIP() []byte {
	file_base_ip_info_proto_rawDescOnce.Do(func() {
		file_base_ip_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_ip_info_proto_rawDescData)
	})
	return file_base_ip_info_proto_rawDescData
}

var file_base_ip_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_base_ip_info_proto_goTypes = []any{
	(*IP_INFO)(nil), // 0: Message.IP_INFO
}
var file_base_ip_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_ip_info_proto_init() }
func file_base_ip_info_proto_init() {
	if File_base_ip_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_ip_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_ip_info_proto_goTypes,
		DependencyIndexes: file_base_ip_info_proto_depIdxs,
		MessageInfos:      file_base_ip_info_proto_msgTypes,
	}.Build()
	File_base_ip_info_proto = out.File
	file_base_ip_info_proto_rawDesc = nil
	file_base_ip_info_proto_goTypes = nil
	file_base_ip_info_proto_depIdxs = nil
}
